apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: login
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nishargsoni/loginbackend:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGODB_URI
              value: mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin
            - name: JWT_SECRET
              value: secret
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: ""
            - name: PORT
              value: "4000"
