apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: login
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nishargsoni/loginfrontend:latest
        ports:
        - containerPort: 80

