apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: login
spec:
  storageClassName: immediate-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
