apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: login
spec:
  storageClassName: immediate-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
